<script type="text/javascript" src="/js/ckeditor/ckeditor.js"></script>
<script type="text/javascript" src="/ckfinder/ckfinder.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<form method="post" enctype="multipart/form-data">
    <fieldset>
        <input type="hidden" name="submitted" value="1" />
        <div class="row">
            <div class="col-sm-6 col-md-6">
                <label for="title"><span style="color:red;">*</span> Title</label>
            </div>
            <div class="col-sm-6 col-md-6">
                <input type="text" name="title" required style="width:100%;"  id="title" value="<?php print $this->model->getTitle(); ?>" />
            </div>
        </div>
        <div class="row" style="margin-top:10px;">
            <div class="col-sm-6 col-md-6">
                <label for="title">Tags (comma separated)</label>
            </div>
            <div class="col-sm-6 col-md-6">
                <input type="text" name="tags" style="width:100%;" id="tags" value="<?php print $this->model->getTags(); ?>" />
            </div>
        </div>
        <div class="row" style="margin-top:10px;">
            <div class="col-sm-6 col-md-6">
                <label for="title"><span style="color:red;">*</span> Date</label>
            </div>
            <div class="col-sm-6 col-md-6">
                <input type="text" name="date" id="date" required value="<?php print $this->model->getDate(); ?>" />
            </div>
        </div>
        <div class="row" style="margin-top:10px;">
            <div class="col-sm-12 col-md-12">
                <textarea name="body" id="body"><?php print $this->model->getBody(); ?></textarea>
                <script>
                //CKEDITOR.replace( 'body' );
                var editor = CKEDITOR.replace( 'body',
                    {
                        filebrowserBrowseUrl : '/ckfinder.html',
                    });
                CKFinder.config.rememberLastFolder = false;
                CKFinder.config.startupPath = "Images:";
                //CKFinder.setupCKEditor( editor, '../' ) ;
                </script>
            </div>
        </div>
        <div class="row" style="margin-top:10px;">
            <input class="btn btn-lg btn-orange col-md-offset-3" type="submit" value="Submit" />
        </div>
    </fieldset>
</form>

<script type="text/javascript">
$(document).ready(function() {
    setTimeout(function(){
       $(".nav li").attr("class", "");  
       $("#blogNav").attr("class", "active"); 
    }, 0);
});
</script>
<script>
  $(function() {
    $( "#date" ).datepicker({
        "dateFormat": 'mm/dd/yy'
    });
  });
  </script>