<script type="text/javascript" src="/js/jscroll.min.js"></script>
<style>
    img {
        -ms-transform: rotate(0deg); /* IE 9 */
        -webkit-transform: rotate(0deg); /* Chrome, Safari, Opera */
        transform: rotate(0deg);
    }
</style>

<?php
$hasIdentity = $this->identityHelper();
if($hasIdentity){
    print '<a href="/blog-post/add">Add a blog post</a><hr />';
}
?>

<div class="blog_box">
    <div class="scroll" data-ui="jscroll-default">
        <?php
        foreach($this->posts as $post){
            $editLink = "";
            $hasIdentity = $this->identityHelper();
            if($hasIdentity){
                $editLink = '<span style="font-size:11px;">&nbsp;&nbsp;<a href="/blog-post/edit/'.$post['id'].'">Edit</a></span>';
            }
            print '<h1>'.$post['title'].$editLink.'</h1>'.$post['body'] . '<hr />';
        }
        ?>
        <div class="next"><a href="/blog-post/load-post/5">next</a></div>
    </div>
</div>

<script type="text/javascript">
$(document).ready(function() {
    setTimeout(function(){
       $(".nav li").attr("class", "");  
       $("#blogNav").attr("class", "active"); 
    }, 0);
    $('.scroll').jscroll({
        loadingHtml: '<div style="width:100%;text-align:center;"><img src="/img/loading_spinner.gif" style="width:75px;" alt="Loading" /></div>'
    });
});
</script>